diff --git a/openerp/addons/base/res/res_users.py b/openerp/addons/base/res/res_users.py
index cb88cb1..b3c7b41 100644
--- a/openerp/addons/base/res/res_users.py
+++ b/openerp/addons/base/res/res_users.py
@@ -444,14 +444,14 @@ class res_users(osv.osv):
                 # another request is holding it. No big deal, we don't want to
                 # prevent/delay login in that case. It will also have been logged
                 # as a SQL error, if anyone cares.
-                try:
+#                try:
                     # NO KEY introduced in PostgreSQL 9.3 http://www.postgresql.org/docs/9.3/static/release-9-3.html#AEN115299
-                    update_clause = 'NO KEY UPDATE' if cr._cnx.server_version >= 90300 else 'UPDATE'
-                    cr.execute("SELECT id FROM res_users WHERE id=%%s FOR %s NOWAIT" % update_clause, (user_id,), log_exceptions=False)
-                    cr.execute("UPDATE res_users SET login_date = now() AT TIME ZONE 'UTC' WHERE id=%s", (user_id,))
-                    self.invalidate_cache(cr, user_id, ['login_date'], [user_id])
-                except Exception:
-                    _logger.debug("Failed to update last_login for db:%s login:%s", db, login, exc_info=True)
+ #                   update_clause = 'NO KEY UPDATE' if cr._cnx.server_version >= 90300 else 'UPDATE'
+  #                  cr.execute("SELECT id FROM res_users WHERE id=%%s FOR %s NOWAIT" % update_clause, (user_id,), log_exceptions=False)
+   #                 cr.execute("UPDATE res_users SET login_date = now() AT TIME ZONE 'UTC' WHERE id=%s", (user_id,))
+    #                self.invalidate_cache(cr, user_id, ['login_date'], [user_id])
+     #           except Exception:
+      #              _logger.debug("Failed to update last_login for db:%s login:%s", db, login, exc_info=True)
